feat: refactor compiler to add compile commands and allow parameterized inputs
Adaptive-Web-Community/Adaptive-Web-Components pull request #190
Opened 2024-04-18 20:42 UTC by nicholasrice

# Pull Request

## Description

This PR does some refactoring of the initial CLI for AUI:
1. It renames the CLI to 'aui'. Users will then run `npx aui <command>`
2. Adds a `compile-style` command to compile a single stylesheet file. This allows customizing the in/out paths as well as the export names for anatomy and styles.
3. Adds a `compile-styles` command that allows bulk globbing of files for processing. The output file extension can be customized, as well as anatomy and styles exports name.
4. Runs the css result through prettier so CSS is readable and not on a single line.
5. Fixes a TypeScript issue where it was trying to compile `dist/**/*.d.ts` files
### Issues

## Reviewer Notes

## Test Plan

## Checklist

### General

- [ ] I have included a change request file using $ npm run change
- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/adaptive-web/adaptive-web-components/blob/master/CONTRIBUTING.md) documentation for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component

## ⏭ Next Steps

2024-04-18 20:44 UTC, KingOfTac approved these changes

2024-04-18 20:44 UTC, nicholasrice commented on change/@adaptive-web-adaptive-ui-ce7bff83-c7cd-440d-84be-62a08db55e7b.json
> +  "type": "patch",
Technically this is breaking because I've changed the CLI command to `aui`. Did the initial version get published?

2024-04-18 20:46 UTC, nicholasrice commented on packages/adaptive-ui/src/aui.ts
> +    // Ensure inFile exists
```suggestion
```

2024-04-18 20:47 UTC, nicholasrice commented on packages/adaptive-ui/tsconfig.json
> +
```suggestion
```

2024-04-18 21:13 UTC, bheston requested changes

2024-04-18 21:13 UTC, bheston commented on packages/adaptive-ui/src/aui.ts
> +        rules: module[stylesName],
This change consolidates the styles and anatomy into the same file, which is fine, but with the way AWC is setup now, the file it processes would need to be the component index. The export names are mixed now, but the anatomy includes the component name like `ButtonAnatomy`. Can we add wildcard support to these parameters?

2024-04-18 21:13 UTC, bheston commented on packages/adaptive-ui/package.json
> +    "aui": "./bin/aui.js"
Can you update AWC `build:styles` to call the new script and args?

2024-04-18 23:03 UTC, bheston commented on packages/adaptive-ui/src/aui.ts
> +    return (`/* This file is generated by AUI from ${path.relative(outFilePath, inFilePath)} */\n`) + formatted;
```suggestion
    return (`/* This file is generated by Adaptive UI from ${path.relative(outFilePath, inFilePath)} */\n`) + formatted;
```

2024-04-19 00:51 UTC, nicholasrice commented on packages/adaptive-ui/src/aui.ts
> +        rules: module[stylesName],
I added a wildcard, I'm confused about AWC though. Doesn't all that compliation happen at runtime in that package? Is it actually building .css files?

2024-04-19 01:24 UTC, bheston commented on packages/adaptive-ui/src/aui.ts
> +        rules: module[stylesName],
AWC doesn't generate css this way. More to keep the proof of concept and test working since the bin has renamed and changed. https://github.com/Adaptive-Web-Community/Adaptive-Web-Components/blob/0da651cbd122edf27d361c452eae3dc4be81dc90/packages/adaptive-web-components/package.json#L26

2024-04-19 01:29 UTC, bheston commented on packages/adaptive-ui/src/aui.ts
> +        rules: module[stylesName],
Kind of a cross with my next comment. It should be something like
`aui compile-styles "dist/esm/components/**/index.js" -a "*Anatomy" -s "*StyleModules"`

2024-04-19 03:39 UTC, nicholasrice-hs commented on packages/adaptive-ui/src/aui.ts
> +        rules: module[stylesName],
Got it, so it's cool if each dir ends up with an `index.css` file instead of what it's doing today?

2024-04-19 04:49 UTC, nicholasrice commented on packages/adaptive-ui/src/aui.ts
> +        rules: module[stylesName],
Pushed this up, it makes an index.css file. If you can think of a good way to re-name files in this case we can look into it, I'm just not sure what the best approach there is from a CLI

2024-04-19 21:40 UTC, bheston approved these changes

2024-04-23 20:55 UTC, merged